export type TypeEmpresas = {
    empr_razaosocial: string;
    empr_codgrupo: string;
    empr_cpfresponsavel: string;
    empr_uf: string;
    empr_contcpf: string;
    empr_contuf: string;
    empr_cnpjcpf: string;
    empr_cargoresponsavel: string;
    empr_cep: string;
    empr_contcrc: string;
    empr_contcep: string;
    empr_inscricaost: string;
    empr_atividade: string;
    empr_inscricaomunicipal: string;
    empr_endereco: string;
    empr_fone: string;
    empr_contendereco: string;
    empr_contfone: string;
    empr_infsociais: string;
    empr_complemento: string;
    empr_fax: string;
    empr_contcomplemento: string;
    empr_contfax: string;
    empr_situacao: string;
    empr_nome: string;
    empr_numero: number;
    empr_email: string;
    empr_contnumero: number;
    empr_contemail: string;
    empr_crt: string;
    empr_codigo: string;
    empr_codqualificacao: string;
    empr_bairro: string;
    empr_contnome: string;
    empr_contbairro: string;
    empr_regjuntacomercial: string;
    empr_numfuncionarios: number;
    empr_nomereduzido: string;
    empr_inscricaoestadual: string;
    empr_responsavel: string;
    empr_codmunicipio: string;
    empr_contcnpj: string;
    empr_contcodmunicipio: string;
    empr_dtdespacho: string | null;
    empr_consultadfe: string;
    empr_municipio: string;
    empr_contmunicipio: string;
    empr_rntrc: string;
    empr_synccrm: string | null;
  };
  