
export async function fetchProdutos() {

  return [
    {
      "Código": "1000",
      "Descrição": "Alias nulla quae",
      "Emp": "4",
      "Descrição Reduzida": "Quisquam",
      "Comple": "Rem",
      "Cod. Categ.": "785",
      "Catego": "Doloremque",
      "Cod. Marca": "573",
      "Marca": "Pires Ltda.",
      "Diretiva": "Fuga",
      "Bal.": false,
      "Codigo Barras": "9398550619874",
      "Codigo NCM": "34090347",
      "Vasilh.": true,
      "CST": "96",
      "Cst Pis": "99",
      "Pis": 1.38,
      "Cst Cofins": "49",
      "Cofins": 2.55,
      "Cest": "8835006",
      "CTS": "dNPc",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 36.28,
      "Pr. Venda 1": 91.16,
      "Pr. Venda 2": 99.64
    },
    {
      "Código": "1001",
      "Descrição": "Voluptatum eos ducimus omnis",
      "Emp": "3",
      "Descrição Reduzida": "Vero",
      "Comple": "Illum",
      "Cod. Categ.": "545",
      "Catego": "Ut",
      "Cod. Marca": "777",
      "Marca": "Lima",
      "Diretiva": "Provident",
      "Bal.": true,
      "Codigo Barras": "7124890897113",
      "Codigo NCM": "45863751",
      "Vasilh.": false,
      "CST": "65",
      "Cst Pis": "67",
      "Pis": 0.92,
      "Cst Cofins": "72",
      "Cofins": 1.13,
      "Cest": "2928217",
      "CTS": "tLqW",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 75.5,
      "Pr. Venda 1": 41.62,
      "Pr. Venda 2": 53.96
    },
    {
      "Código": "1002",
      "Descrição": "Vitae ex quasi molestiae est",
      "Emp": "2",
      "Descrição Reduzida": "Ea",
      "Comple": "Recusandae",
      "Cod. Categ.": "857",
      "Catego": "Dolore",
      "Cod. Marca": "952",
      "Marca": "Monteiro Silva S/A",
      "Diretiva": "Reprehenderit",
      "Bal.": true,
      "Codigo Barras": "7143078214252",
      "Codigo NCM": "95205311",
      "Vasilh.": true,
      "CST": "12",
      "Cst Pis": "46",
      "Pis": 0.87,
      "Cst Cofins": "29",
      "Cofins": 2.03,
      "Cest": "6688317",
      "CTS": "LMQQ",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 57.21,
      "Pr. Venda 1": 18.31,
      "Pr. Venda 2": 20.08
    },
    {
      "Código": "1003",
      "Descrição": "Sint iusto nobis fugiat",
      "Emp": "3",
      "Descrição Reduzida": "Est",
      "Comple": "Alias",
      "Cod. Categ.": "463",
      "Catego": "Ducimus",
      "Cod. Marca": "632",
      "Marca": "Moreira Ltda.",
      "Diretiva": "Quaerat",
      "Bal.": false,
      "Codigo Barras": "9054126621862",
      "Codigo NCM": "11406532",
      "Vasilh.": false,
      "CST": "45",
      "Cst Pis": "39",
      "Pis": 0.93,
      "Cst Cofins": "44",
      "Cofins": 1.23,
      "Cest": "5896615",
      "CTS": "YQOM",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 15.07,
      "Pr. Venda 1": 29.24,
      "Pr. Venda 2": 62.38
    },
    {
      "Código": "1004",
      "Descrição": "Modi nisi debitis possimus",
      "Emp": "5",
      "Descrição Reduzida": "Voluptatem",
      "Comple": "Eius",
      "Cod. Categ.": "921",
      "Catego": "Ullam",
      "Cod. Marca": "445",
      "Marca": "da Cunha Costela Ltda.",
      "Diretiva": "Aliquam",
      "Bal.": false,
      "Codigo Barras": "6575741735862",
      "Codigo NCM": "12104397",
      "Vasilh.": false,
      "CST": "06",
      "Cst Pis": "87",
      "Pis": 1.91,
      "Cst Cofins": "60",
      "Cofins": 2.86,
      "Cest": "2918134",
      "CTS": "pAOB",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 69.97,
      "Pr. Venda 1": 24.93,
      "Pr. Venda 2": 84.57
    },
    {
      "Código": "1005",
      "Descrição": "Quae voluptatibus eaque",
      "Emp": "2",
      "Descrição Reduzida": "Harum",
      "Comple": "Distinctio",
      "Cod. Categ.": "828",
      "Catego": "Architecto",
      "Cod. Marca": "565",
      "Marca": "Barros S/A",
      "Diretiva": "Dolorum",
      "Bal.": true,
      "Codigo Barras": "3214668686552",
      "Codigo NCM": "33608208",
      "Vasilh.": false,
      "CST": "79",
      "Cst Pis": "36",
      "Pis": 1.87,
      "Cst Cofins": "28",
      "Cofins": 2.84,
      "Cest": "4867239",
      "CTS": "gPco",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 27.58,
      "Pr. Venda 1": 98.71,
      "Pr. Venda 2": 51.1
    },
    {
      "Código": "1006",
      "Descrição": "Impedit voluptatem libero",
      "Emp": "2",
      "Descrição Reduzida": "Consectetur",
      "Comple": "Magni",
      "Cod. Categ.": "583",
      "Catego": "Odio",
      "Cod. Marca": "368",
      "Marca": "Nunes Ferreira Ltda.",
      "Diretiva": "Expedita",
      "Bal.": true,
      "Codigo Barras": "6188572930568",
      "Codigo NCM": "77702729",
      "Vasilh.": false,
      "CST": "44",
      "Cst Pis": "15",
      "Pis": 1.16,
      "Cst Cofins": "57",
      "Cofins": 1.99,
      "Cest": "7016196",
      "CTS": "ZMdR",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 46.61,
      "Pr. Venda 1": 31.1,
      "Pr. Venda 2": 98.51
    },
    {
      "Código": "1007",
      "Descrição": "Nihil sed molestias id",
      "Emp": "4",
      "Descrição Reduzida": "Deleniti",
      "Comple": "Natus",
      "Cod. Categ.": "886",
      "Catego": "Quaerat",
      "Cod. Marca": "535",
      "Marca": "Moura",
      "Diretiva": "Id",
      "Bal.": true,
      "Codigo Barras": "8471067883769",
      "Codigo NCM": "91026829",
      "Vasilh.": true,
      "CST": "79",
      "Cst Pis": "30",
      "Pis": 1.2,
      "Cst Cofins": "13",
      "Cofins": 2.15,
      "Cest": "7077225",
      "CTS": "ATuD",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 66.75,
      "Pr. Venda 1": 89.07,
      "Pr. Venda 2": 79.04
    },
    {
      "Código": "1008",
      "Descrição": "Dolores alias quae earum",
      "Emp": "1",
      "Descrição Reduzida": "Architecto",
      "Comple": "Eius",
      "Cod. Categ.": "808",
      "Catego": "Eligendi",
      "Cod. Marca": "562",
      "Marca": "Silva",
      "Diretiva": "Totam",
      "Bal.": true,
      "Codigo Barras": "3879333398019",
      "Codigo NCM": "10876680",
      "Vasilh.": false,
      "CST": "38",
      "Cst Pis": "12",
      "Pis": 1.76,
      "Cst Cofins": "04",
      "Cofins": 1.95,
      "Cest": "5973361",
      "CTS": "acVK",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 20.15,
      "Pr. Venda 1": 90.85,
      "Pr. Venda 2": 40.46
    },
    {
      "Código": "1009",
      "Descrição": "Sit optio temporibus",
      "Emp": "4",
      "Descrição Reduzida": "Aliquid",
      "Comple": "Sapiente",
      "Cod. Categ.": "821",
      "Catego": "Distinctio",
      "Cod. Marca": "765",
      "Marca": "Caldeira Melo e Filhos",
      "Diretiva": "Temporibus",
      "Bal.": false,
      "Codigo Barras": "0858616795120",
      "Codigo NCM": "16587943",
      "Vasilh.": true,
      "CST": "57",
      "Cst Pis": "26",
      "Pis": 1.05,
      "Cst Cofins": "70",
      "Cofins": 1.0,
      "Cest": "7386889",
      "CTS": "icXk",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 52.74,
      "Pr. Venda 1": 53.91,
      "Pr. Venda 2": 97.33
    },
    {
      "Código": "1010",
      "Descrição": "Error natus sint officia",
      "Emp": "4",
      "Descrição Reduzida": "Maiores",
      "Comple": "Provident",
      "Cod. Categ.": "568",
      "Catego": "Facilis",
      "Cod. Marca": "601",
      "Marca": "Azevedo S/A",
      "Diretiva": "Nostrum",
      "Bal.": true,
      "Codigo Barras": "7846190050493",
      "Codigo NCM": "60617616",
      "Vasilh.": true,
      "CST": "11",
      "Cst Pis": "76",
      "Pis": 1.49,
      "Cst Cofins": "46",
      "Cofins": 2.33,
      "Cest": "4302277",
      "CTS": "bjRW",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 30.1,
      "Pr. Venda 1": 23.23,
      "Pr. Venda 2": 61.95
    },
    {
      "Código": "1011",
      "Descrição": "Placeat nesciunt ducimus",
      "Emp": "3",
      "Descrição Reduzida": "Vitae",
      "Comple": "Corporis",
      "Cod. Categ.": "583",
      "Catego": "Voluptatum",
      "Cod. Marca": "812",
      "Marca": "Azevedo",
      "Diretiva": "Sed",
      "Bal.": true,
      "Codigo Barras": "7741097066496",
      "Codigo NCM": "75836276",
      "Vasilh.": false,
      "CST": "03",
      "Cst Pis": "96",
      "Pis": 1.52,
      "Cst Cofins": "82",
      "Cofins": 1.17,
      "Cest": "4458036",
      "CTS": "PcEP",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 99.98,
      "Pr. Venda 1": 73.29,
      "Pr. Venda 2": 81.93
    },
    {
      "Código": "1012",
      "Descrição": "Vitae quas repellat officia",
      "Emp": "2",
      "Descrição Reduzida": "Repellat",
      "Comple": "Cupiditate",
      "Cod. Categ.": "919",
      "Catego": "Corporis",
      "Cod. Marca": "862",
      "Marca": "da Rosa Moreira Ltda.",
      "Diretiva": "Aspernatur",
      "Bal.": true,
      "Codigo Barras": "3206685621685",
      "Codigo NCM": "68017611",
      "Vasilh.": false,
      "CST": "08",
      "Cst Pis": "85",
      "Pis": 1.85,
      "Cst Cofins": "24",
      "Cofins": 2.81,
      "Cest": "9320897",
      "CTS": "XpwF",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 61.89,
      "Pr. Venda 1": 20.9,
      "Pr. Venda 2": 70.9
    },
    {
      "Código": "1013",
      "Descrição": "Explicabo excepturi amet",
      "Emp": "3",
      "Descrição Reduzida": "Quisquam",
      "Comple": "Repellendus",
      "Cod. Categ.": "199",
      "Catego": "Molestias",
      "Cod. Marca": "557",
      "Marca": "da Rocha",
      "Diretiva": "Mollitia",
      "Bal.": false,
      "Codigo Barras": "4833640102690",
      "Codigo NCM": "67460324",
      "Vasilh.": true,
      "CST": "82",
      "Cst Pis": "79",
      "Pis": 1.91,
      "Cst Cofins": "57",
      "Cofins": 2.99,
      "Cest": "5466216",
      "CTS": "pLHu",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 33.41,
      "Pr. Venda 1": 27.13,
      "Pr. Venda 2": 54.85
    },
    {
      "Código": "1014",
      "Descrição": "Culpa ea praesentium quo",
      "Emp": "5",
      "Descrição Reduzida": "Repellendus",
      "Comple": "Reiciendis",
      "Cod. Categ.": "533",
      "Catego": "Quidem",
      "Cod. Marca": "543",
      "Marca": "Martins Porto Ltda.",
      "Diretiva": "Porro",
      "Bal.": false,
      "Codigo Barras": "1833915240464",
      "Codigo NCM": "52779998",
      "Vasilh.": false,
      "CST": "89",
      "Cst Pis": "36",
      "Pis": 0.77,
      "Cst Cofins": "72",
      "Cofins": 1.14,
      "Cest": "2170208",
      "CTS": "OLPL",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 66.05,
      "Pr. Venda 1": 55.41,
      "Pr. Venda 2": 42.72
    },
    {
      "Código": "1015",
      "Descrição": "Fuga illo quis",
      "Emp": "5",
      "Descrição Reduzida": "Eligendi",
      "Comple": "Labore",
      "Cod. Categ.": "844",
      "Catego": "Voluptates",
      "Cod. Marca": "646",
      "Marca": "da Rosa e Filhos",
      "Diretiva": "Necessitatibus",
      "Bal.": true,
      "Codigo Barras": "1809045415027",
      "Codigo NCM": "85053644",
      "Vasilh.": true,
      "CST": "15",
      "Cst Pis": "18",
      "Pis": 1.52,
      "Cst Cofins": "05",
      "Cofins": 2.0,
      "Cest": "6197409",
      "CTS": "EaVn",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 86.09,
      "Pr. Venda 1": 66.61,
      "Pr. Venda 2": 56.7
    },
    {
      "Código": "1016",
      "Descrição": "Totam est aspernatur",
      "Emp": "3",
      "Descrição Reduzida": "Iste",
      "Comple": "Unde",
      "Cod. Categ.": "129",
      "Catego": "Possimus",
      "Cod. Marca": "547",
      "Marca": "Sales",
      "Diretiva": "Dicta",
      "Bal.": true,
      "Codigo Barras": "4062764138326",
      "Codigo NCM": "87245715",
      "Vasilh.": true,
      "CST": "11",
      "Cst Pis": "41",
      "Pis": 1.63,
      "Cst Cofins": "86",
      "Cofins": 2.63,
      "Cest": "8854747",
      "CTS": "vgvs",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 45.69,
      "Pr. Venda 1": 87.91,
      "Pr. Venda 2": 14.49
    },
    {
      "Código": "1017",
      "Descrição": "Sit aliquam aliquam fugit",
      "Emp": "3",
      "Descrição Reduzida": "Non",
      "Comple": "Voluptatibus",
      "Cod. Categ.": "153",
      "Catego": "Non",
      "Cod. Marca": "376",
      "Marca": "Pereira Vieira - ME",
      "Diretiva": "Qui",
      "Bal.": false,
      "Codigo Barras": "4578489872662",
      "Codigo NCM": "33368318",
      "Vasilh.": false,
      "CST": "95",
      "Cst Pis": "81",
      "Pis": 1.74,
      "Cst Cofins": "85",
      "Cofins": 1.99,
      "Cest": "5562435",
      "CTS": "Tctd",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 54.29,
      "Pr. Venda 1": 63.46,
      "Pr. Venda 2": 51.3
    },
    {
      "Código": "1018",
      "Descrição": "Autem sint iste veritatis",
      "Emp": "3",
      "Descrição Reduzida": "Veniam",
      "Comple": "Facere",
      "Cod. Categ.": "428",
      "Catego": "Totam",
      "Cod. Marca": "613",
      "Marca": "Fogaça",
      "Diretiva": "Blanditiis",
      "Bal.": false,
      "Codigo Barras": "9177127518662",
      "Codigo NCM": "63242672",
      "Vasilh.": false,
      "CST": "13",
      "Cst Pis": "69",
      "Pis": 1.03,
      "Cst Cofins": "24",
      "Cofins": 1.27,
      "Cest": "3511061",
      "CTS": "dmgh",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 30.99,
      "Pr. Venda 1": 46.6,
      "Pr. Venda 2": 60.0
    },
    {
      "Código": "1019",
      "Descrição": "Ducimus eius nihil",
      "Emp": "1",
      "Descrição Reduzida": "Molestiae",
      "Comple": "Sit",
      "Cod. Categ.": "180",
      "Catego": "Cumque",
      "Cod. Marca": "915",
      "Marca": "Silveira Fogaça e Filhos",
      "Diretiva": "Amet",
      "Bal.": false,
      "Codigo Barras": "6852741639148",
      "Codigo NCM": "44178635",
      "Vasilh.": false,
      "CST": "85",
      "Cst Pis": "76",
      "Pis": 1.36,
      "Cst Cofins": "09",
      "Cofins": 2.04,
      "Cest": "8008350",
      "CTS": "vzkg",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 43.79,
      "Pr. Venda 1": 57.0,
      "Pr. Venda 2": 26.4
    },
    {
      "Código": "1020",
      "Descrição": "Consequatur quasi labore",
      "Emp": "3",
      "Descrição Reduzida": "Vel",
      "Comple": "Quidem",
      "Cod. Categ.": "934",
      "Catego": "Cum",
      "Cod. Marca": "717",
      "Marca": "Moraes Ltda.",
      "Diretiva": "Impedit",
      "Bal.": true,
      "Codigo Barras": "7682078102164",
      "Codigo NCM": "96302761",
      "Vasilh.": false,
      "CST": "33",
      "Cst Pis": "82",
      "Pis": 0.65,
      "Cst Cofins": "09",
      "Cofins": 1.89,
      "Cest": "2211939",
      "CTS": "MGJG",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 67.29,
      "Pr. Venda 1": 34.36,
      "Pr. Venda 2": 91.25
    },
    {
      "Código": "1021",
      "Descrição": "Ducimus dolor debitis ut",
      "Emp": "3",
      "Descrição Reduzida": "Cumque",
      "Comple": "Iste",
      "Cod. Categ.": "449",
      "Catego": "Sapiente",
      "Cod. Marca": "793",
      "Marca": "Correia e Filhos",
      "Diretiva": "Nostrum",
      "Bal.": true,
      "Codigo Barras": "2648500756041",
      "Codigo NCM": "64205099",
      "Vasilh.": true,
      "CST": "17",
      "Cst Pis": "77",
      "Pis": 1.27,
      "Cst Cofins": "60",
      "Cofins": 2.33,
      "Cest": "2525472",
      "CTS": "nzjz",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 32.65,
      "Pr. Venda 1": 35.35,
      "Pr. Venda 2": 15.99
    },
    {
      "Código": "1022",
      "Descrição": "Esse doloremque corporis non",
      "Emp": "3",
      "Descrição Reduzida": "Voluptate",
      "Comple": "Corporis",
      "Cod. Categ.": "790",
      "Catego": "Officiis",
      "Cod. Marca": "273",
      "Marca": "Novaes",
      "Diretiva": "Quasi",
      "Bal.": true,
      "Codigo Barras": "7489487223349",
      "Codigo NCM": "75076376",
      "Vasilh.": false,
      "CST": "06",
      "Cst Pis": "97",
      "Pis": 1.55,
      "Cst Cofins": "68",
      "Cofins": 2.03,
      "Cest": "3300093",
      "CTS": "tNAW",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 42.96,
      "Pr. Venda 1": 10.26,
      "Pr. Venda 2": 85.37
    },
    {
      "Código": "1023",
      "Descrição": "Odio ab molestiae",
      "Emp": "4",
      "Descrição Reduzida": "Tenetur",
      "Comple": "A",
      "Cod. Categ.": "240",
      "Catego": "Eius",
      "Cod. Marca": "982",
      "Marca": "Novaes Martins S/A",
      "Diretiva": "Architecto",
      "Bal.": false,
      "Codigo Barras": "4274029462033",
      "Codigo NCM": "38040830",
      "Vasilh.": false,
      "CST": "97",
      "Cst Pis": "35",
      "Pis": 1.96,
      "Cst Cofins": "80",
      "Cofins": 1.41,
      "Cest": "8778176",
      "CTS": "AfOu",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 60.37,
      "Pr. Venda 1": 23.4,
      "Pr. Venda 2": 92.59
    },
    {
      "Código": "1024",
      "Descrição": "Maxime doloremque ea",
      "Emp": "1",
      "Descrição Reduzida": "Impedit",
      "Comple": "Quis",
      "Cod. Categ.": "946",
      "Catego": "Nulla",
      "Cod. Marca": "256",
      "Marca": "Aragão",
      "Diretiva": "Dolor",
      "Bal.": false,
      "Codigo Barras": "8742438078436",
      "Codigo NCM": "41155587",
      "Vasilh.": true,
      "CST": "68",
      "Cst Pis": "73",
      "Pis": 1.76,
      "Cst Cofins": "83",
      "Cofins": 1.48,
      "Cest": "3290381",
      "CTS": "Uyma",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 34.55,
      "Pr. Venda 1": 62.77,
      "Pr. Venda 2": 36.25
    },
    {
      "Código": "1025",
      "Descrição": "Illum rerum aliquam cum",
      "Emp": "1",
      "Descrição Reduzida": "Possimus",
      "Comple": "Excepturi",
      "Cod. Categ.": "177",
      "Catego": "Ut",
      "Cod. Marca": "738",
      "Marca": "Mendes",
      "Diretiva": "Voluptates",
      "Bal.": false,
      "Codigo Barras": "3286147450312",
      "Codigo NCM": "54227764",
      "Vasilh.": true,
      "CST": "99",
      "Cst Pis": "47",
      "Pis": 1.77,
      "Cst Cofins": "44",
      "Cofins": 2.99,
      "Cest": "7123826",
      "CTS": "CHyj",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 39.47,
      "Pr. Venda 1": 14.75,
      "Pr. Venda 2": 55.33
    },
    {
      "Código": "1026",
      "Descrição": "Quisquam nihil earum eos",
      "Emp": "3",
      "Descrição Reduzida": "Veritatis",
      "Comple": "Odit",
      "Cod. Categ.": "116",
      "Catego": "Rem",
      "Cod. Marca": "600",
      "Marca": "das Neves da Rosa S/A",
      "Diretiva": "Necessitatibus",
      "Bal.": false,
      "Codigo Barras": "7245316172772",
      "Codigo NCM": "55572878",
      "Vasilh.": false,
      "CST": "35",
      "Cst Pis": "80",
      "Pis": 1.04,
      "Cst Cofins": "73",
      "Cofins": 1.61,
      "Cest": "5347892",
      "CTS": "OqYW",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 54.73,
      "Pr. Venda 1": 73.2,
      "Pr. Venda 2": 26.58
    },
    {
      "Código": "1027",
      "Descrição": "Eius enim veritatis",
      "Emp": "5",
      "Descrição Reduzida": "Iure",
      "Comple": "Molestias",
      "Cod. Categ.": "887",
      "Catego": "Dolore",
      "Cod. Marca": "711",
      "Marca": "Fogaça S/A",
      "Diretiva": "Quis",
      "Bal.": true,
      "Codigo Barras": "1299802394618",
      "Codigo NCM": "77624984",
      "Vasilh.": true,
      "CST": "12",
      "Cst Pis": "21",
      "Pis": 1.82,
      "Cst Cofins": "30",
      "Cofins": 1.66,
      "Cest": "9880850",
      "CTS": "gHHO",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 31.21,
      "Pr. Venda 1": 42.17,
      "Pr. Venda 2": 48.31
    },
    {
      "Código": "1028",
      "Descrição": "At cum eveniet odit a itaque",
      "Emp": "5",
      "Descrição Reduzida": "Totam",
      "Comple": "Reiciendis",
      "Cod. Categ.": "623",
      "Catego": "Deleniti",
      "Cod. Marca": "583",
      "Marca": "Melo Lopes e Filhos",
      "Diretiva": "Minima",
      "Bal.": false,
      "Codigo Barras": "3574408531680",
      "Codigo NCM": "90460670",
      "Vasilh.": true,
      "CST": "86",
      "Cst Pis": "71",
      "Pis": 1.93,
      "Cst Cofins": "60",
      "Cofins": 1.99,
      "Cest": "5562863",
      "CTS": "UTUo",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 60.32,
      "Pr. Venda 1": 11.86,
      "Pr. Venda 2": 28.17
    },
    {
      "Código": "1029",
      "Descrição": "Saepe facere tenetur esse ut",
      "Emp": "2",
      "Descrição Reduzida": "Excepturi",
      "Comple": "Omnis",
      "Cod. Categ.": "838",
      "Catego": "Natus",
      "Cod. Marca": "294",
      "Marca": "Silveira",
      "Diretiva": "Odit",
      "Bal.": false,
      "Codigo Barras": "6224394552998",
      "Codigo NCM": "21881681",
      "Vasilh.": true,
      "CST": "51",
      "Cst Pis": "55",
      "Pis": 0.76,
      "Cst Cofins": "88",
      "Cofins": 1.87,
      "Cest": "9184883",
      "CTS": "KjFY",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 35.44,
      "Pr. Venda 1": 96.8,
      "Pr. Venda 2": 70.04
    },
    {
      "Código": "1030",
      "Descrição": "Iure ut consequatur aut",
      "Emp": "1",
      "Descrição Reduzida": "Tempore",
      "Comple": "Nobis",
      "Cod. Categ.": "968",
      "Catego": "Nemo",
      "Cod. Marca": "297",
      "Marca": "Cunha",
      "Diretiva": "Aspernatur",
      "Bal.": true,
      "Codigo Barras": "0585817765248",
      "Codigo NCM": "88306296",
      "Vasilh.": false,
      "CST": "43",
      "Cst Pis": "32",
      "Pis": 0.78,
      "Cst Cofins": "63",
      "Cofins": 1.57,
      "Cest": "2345539",
      "CTS": "yZnf",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 25.33,
      "Pr. Venda 1": 99.23,
      "Pr. Venda 2": 64.98
    },
    {
      "Código": "1031",
      "Descrição": "Eveniet est sunt est",
      "Emp": "1",
      "Descrição Reduzida": "Necessitatibus",
      "Comple": "Accusantium",
      "Cod. Categ.": "848",
      "Catego": "Odio",
      "Cod. Marca": "683",
      "Marca": "Cardoso e Filhos",
      "Diretiva": "Quis",
      "Bal.": false,
      "Codigo Barras": "6699273861360",
      "Codigo NCM": "49993645",
      "Vasilh.": false,
      "CST": "17",
      "Cst Pis": "74",
      "Pis": 1.67,
      "Cst Cofins": "69",
      "Cofins": 1.36,
      "Cest": "7703784",
      "CTS": "sNNP",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 38.55,
      "Pr. Venda 1": 83.78,
      "Pr. Venda 2": 17.57
    },
    {
      "Código": "1032",
      "Descrição": "Nisi quod ad",
      "Emp": "1",
      "Descrição Reduzida": "Perspiciatis",
      "Comple": "Dolore",
      "Cod. Categ.": "440",
      "Catego": "Tenetur",
      "Cod. Marca": "668",
      "Marca": "Rocha",
      "Diretiva": "Corrupti",
      "Bal.": false,
      "Codigo Barras": "3413926324773",
      "Codigo NCM": "48089880",
      "Vasilh.": true,
      "CST": "12",
      "Cst Pis": "11",
      "Pis": 0.74,
      "Cst Cofins": "29",
      "Cofins": 2.7,
      "Cest": "1708030",
      "CTS": "FFOi",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 44.81,
      "Pr. Venda 1": 86.89,
      "Pr. Venda 2": 55.15
    },
    {
      "Código": "1033",
      "Descrição": "Corporis nisi laborum",
      "Emp": "5",
      "Descrição Reduzida": "Repellat",
      "Comple": "Impedit",
      "Cod. Categ.": "319",
      "Catego": "Quae",
      "Cod. Marca": "361",
      "Marca": "Mendes S/A",
      "Diretiva": "Nobis",
      "Bal.": true,
      "Codigo Barras": "5006288439797",
      "Codigo NCM": "45141997",
      "Vasilh.": true,
      "CST": "50",
      "Cst Pis": "02",
      "Pis": 1.05,
      "Cst Cofins": "56",
      "Cofins": 2.63,
      "Cest": "4631204",
      "CTS": "wTNg",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 81.88,
      "Pr. Venda 1": 65.25,
      "Pr. Venda 2": 97.09
    },
    {
      "Código": "1034",
      "Descrição": "Qui error soluta velit",
      "Emp": "3",
      "Descrição Reduzida": "Perferendis",
      "Comple": "Expedita",
      "Cod. Categ.": "556",
      "Catego": "Illum",
      "Cod. Marca": "747",
      "Marca": "Silveira",
      "Diretiva": "Quod",
      "Bal.": true,
      "Codigo Barras": "5884738896426",
      "Codigo NCM": "43459803",
      "Vasilh.": false,
      "CST": "31",
      "Cst Pis": "47",
      "Pis": 1.39,
      "Cst Cofins": "05",
      "Cofins": 2.65,
      "Cest": "6099608",
      "CTS": "ZUTm",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 98.6,
      "Pr. Venda 1": 28.03,
      "Pr. Venda 2": 33.83
    },
    {
      "Código": "1035",
      "Descrição": "Atque aperiam labore magni",
      "Emp": "3",
      "Descrição Reduzida": "Facilis",
      "Comple": "Consectetur",
      "Cod. Categ.": "312",
      "Catego": "Iusto",
      "Cod. Marca": "427",
      "Marca": "Dias",
      "Diretiva": "Laboriosam",
      "Bal.": false,
      "Codigo Barras": "9310216395045",
      "Codigo NCM": "70935041",
      "Vasilh.": true,
      "CST": "63",
      "Cst Pis": "63",
      "Pis": 1.49,
      "Cst Cofins": "36",
      "Cofins": 1.52,
      "Cest": "4879083",
      "CTS": "ovig",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 72.9,
      "Pr. Venda 1": 51.13,
      "Pr. Venda 2": 65.55
    },
    {
      "Código": "1036",
      "Descrição": "Repudiandae at in nemo vitae",
      "Emp": "1",
      "Descrição Reduzida": "Explicabo",
      "Comple": "Vero",
      "Cod. Categ.": "518",
      "Catego": "Delectus",
      "Cod. Marca": "843",
      "Marca": "Silveira Nunes e Filhos",
      "Diretiva": "Aperiam",
      "Bal.": false,
      "Codigo Barras": "0915987435434",
      "Codigo NCM": "64428569",
      "Vasilh.": false,
      "CST": "39",
      "Cst Pis": "94",
      "Pis": 1.53,
      "Cst Cofins": "17",
      "Cofins": 1.44,
      "Cest": "9200779",
      "CTS": "waRO",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 72.19,
      "Pr. Venda 1": 86.66,
      "Pr. Venda 2": 22.89
    },
    {
      "Código": "1037",
      "Descrição": "Qui autem ipsam autem",
      "Emp": "3",
      "Descrição Reduzida": "Blanditiis",
      "Comple": "Aspernatur",
      "Cod. Categ.": "418",
      "Catego": "Quas",
      "Cod. Marca": "653",
      "Marca": "da Conceição",
      "Diretiva": "Officia",
      "Bal.": true,
      "Codigo Barras": "3453992727665",
      "Codigo NCM": "52187498",
      "Vasilh.": false,
      "CST": "02",
      "Cst Pis": "89",
      "Pis": 1.34,
      "Cst Cofins": "12",
      "Cofins": 1.2,
      "Cest": "5362217",
      "CTS": "KIdf",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 65.14,
      "Pr. Venda 1": 77.81,
      "Pr. Venda 2": 64.6
    },
    {
      "Código": "1038",
      "Descrição": "Optio quisquam nihil fugit",
      "Emp": "2",
      "Descrição Reduzida": "Dolor",
      "Comple": "Ipsa",
      "Cod. Categ.": "373",
      "Catego": "Facilis",
      "Cod. Marca": "743",
      "Marca": "Duarte Ltda.",
      "Diretiva": "Reiciendis",
      "Bal.": false,
      "Codigo Barras": "3882191644242",
      "Codigo NCM": "88501945",
      "Vasilh.": false,
      "CST": "42",
      "Cst Pis": "40",
      "Pis": 1.3,
      "Cst Cofins": "29",
      "Cofins": 1.43,
      "Cest": "5665373",
      "CTS": "wMFJ",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 58.02,
      "Pr. Venda 1": 75.83,
      "Pr. Venda 2": 15.43
    },
    {
      "Código": "1039",
      "Descrição": "Omnis voluptatem consectetur",
      "Emp": "4",
      "Descrição Reduzida": "Aut",
      "Comple": "Quibusdam",
      "Cod. Categ.": "887",
      "Catego": "Explicabo",
      "Cod. Marca": "269",
      "Marca": "Moreira S/A",
      "Diretiva": "Nihil",
      "Bal.": true,
      "Codigo Barras": "0343554565480",
      "Codigo NCM": "38676742",
      "Vasilh.": true,
      "CST": "49",
      "Cst Pis": "83",
      "Pis": 1.63,
      "Cst Cofins": "32",
      "Cofins": 2.62,
      "Cest": "9459378",
      "CTS": "wtdg",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 10.82,
      "Pr. Venda 1": 72.53,
      "Pr. Venda 2": 66.48
    },
    {
      "Código": "1040",
      "Descrição": "Ipsam praesentium vitae",
      "Emp": "5",
      "Descrição Reduzida": "Praesentium",
      "Comple": "Reprehenderit",
      "Cod. Categ.": "729",
      "Catego": "Alias",
      "Cod. Marca": "534",
      "Marca": "Almeida e Filhos",
      "Diretiva": "Possimus",
      "Bal.": true,
      "Codigo Barras": "5820410018083",
      "Codigo NCM": "17720489",
      "Vasilh.": false,
      "CST": "90",
      "Cst Pis": "73",
      "Pis": 1.51,
      "Cst Cofins": "14",
      "Cofins": 1.57,
      "Cest": "5315544",
      "CTS": "Lqsi",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 86.72,
      "Pr. Venda 1": 97.58,
      "Pr. Venda 2": 56.5
    },
    {
      "Código": "1041",
      "Descrição": "Debitis odit ducimus",
      "Emp": "3",
      "Descrição Reduzida": "Nihil",
      "Comple": "Dicta",
      "Cod. Categ.": "667",
      "Catego": "Blanditiis",
      "Cod. Marca": "248",
      "Marca": "Lopes",
      "Diretiva": "Magnam",
      "Bal.": false,
      "Codigo Barras": "2788457201451",
      "Codigo NCM": "22348860",
      "Vasilh.": false,
      "CST": "25",
      "Cst Pis": "87",
      "Pis": 1.87,
      "Cst Cofins": "19",
      "Cofins": 1.72,
      "Cest": "3692918",
      "CTS": "eNYR",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 49.57,
      "Pr. Venda 1": 29.48,
      "Pr. Venda 2": 76.72
    },
    {
      "Código": "1042",
      "Descrição": "Unde quae ad cum",
      "Emp": "1",
      "Descrição Reduzida": "Modi",
      "Comple": "Earum",
      "Cod. Categ.": "924",
      "Catego": "Adipisci",
      "Cod. Marca": "691",
      "Marca": "Campos",
      "Diretiva": "Aperiam",
      "Bal.": false,
      "Codigo Barras": "4773320209090",
      "Codigo NCM": "69809167",
      "Vasilh.": false,
      "CST": "01",
      "Cst Pis": "48",
      "Pis": 1.74,
      "Cst Cofins": "96",
      "Cofins": 1.56,
      "Cest": "7789466",
      "CTS": "srlC",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 69.71,
      "Pr. Venda 1": 55.62,
      "Pr. Venda 2": 61.78
    },
    {
      "Código": "1043",
      "Descrição": "Eos aliquid illo ducimus",
      "Emp": "4",
      "Descrição Reduzida": "Sequi",
      "Comple": "Exercitationem",
      "Cod. Categ.": "699",
      "Catego": "Dolorum",
      "Cod. Marca": "597",
      "Marca": "Lima Ltda.",
      "Diretiva": "Dolore",
      "Bal.": true,
      "Codigo Barras": "4293661851333",
      "Codigo NCM": "63205533",
      "Vasilh.": true,
      "CST": "67",
      "Cst Pis": "68",
      "Pis": 1.03,
      "Cst Cofins": "75",
      "Cofins": 1.64,
      "Cest": "5790736",
      "CTS": "EQeB",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 87.69,
      "Pr. Venda 1": 28.81,
      "Pr. Venda 2": 92.28
    },
    {
      "Código": "1044",
      "Descrição": "Aperiam quibusdam in rerum",
      "Emp": "5",
      "Descrição Reduzida": "Quibusdam",
      "Comple": "Corporis",
      "Cod. Categ.": "107",
      "Catego": "Mollitia",
      "Cod. Marca": "816",
      "Marca": "da Mota Moura S.A.",
      "Diretiva": "Delectus",
      "Bal.": true,
      "Codigo Barras": "0094232486770",
      "Codigo NCM": "93150525",
      "Vasilh.": true,
      "CST": "98",
      "Cst Pis": "16",
      "Pis": 0.66,
      "Cst Cofins": "35",
      "Cofins": 2.19,
      "Cest": "7394019",
      "CTS": "ymmJ",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 67.69,
      "Pr. Venda 1": 82.2,
      "Pr. Venda 2": 78.96
    },
    {
      "Código": "1045",
      "Descrição": "Aliquam in soluta dicta",
      "Emp": "5",
      "Descrição Reduzida": "Placeat",
      "Comple": "Sit",
      "Cod. Categ.": "745",
      "Catego": "Praesentium",
      "Cod. Marca": "331",
      "Marca": "Pinto e Filhos",
      "Diretiva": "Voluptate",
      "Bal.": false,
      "Codigo Barras": "8268071327057",
      "Codigo NCM": "47255002",
      "Vasilh.": false,
      "CST": "41",
      "Cst Pis": "52",
      "Pis": 0.72,
      "Cst Cofins": "02",
      "Cofins": 1.29,
      "Cest": "9831242",
      "CTS": "ECnd",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 36.74,
      "Pr. Venda 1": 89.07,
      "Pr. Venda 2": 92.38
    },
    {
      "Código": "1046",
      "Descrição": "Reiciendis fugiat saepe",
      "Emp": "4",
      "Descrição Reduzida": "Ratione",
      "Comple": "Velit",
      "Cod. Categ.": "820",
      "Catego": "Ab",
      "Cod. Marca": "639",
      "Marca": "Viana Melo - EI",
      "Diretiva": "Excepturi",
      "Bal.": false,
      "Codigo Barras": "2018982248882",
      "Codigo NCM": "58880437",
      "Vasilh.": false,
      "CST": "83",
      "Cst Pis": "11",
      "Pis": 1.46,
      "Cst Cofins": "57",
      "Cofins": 1.99,
      "Cest": "2022236",
      "CTS": "gXpS",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 91.34,
      "Pr. Venda 1": 35.89,
      "Pr. Venda 2": 30.37
    },
    {
      "Código": "1047",
      "Descrição": "Velit ullam ducimus ad",
      "Emp": "2",
      "Descrição Reduzida": "Consequatur",
      "Comple": "Eaque",
      "Cod. Categ.": "945",
      "Catego": "Consectetur",
      "Cod. Marca": "595",
      "Marca": "da Conceição da Cruz S/A",
      "Diretiva": "Numquam",
      "Bal.": true,
      "Codigo Barras": "5301443264178",
      "Codigo NCM": "62753316",
      "Vasilh.": false,
      "CST": "32",
      "Cst Pis": "52",
      "Pis": 1.19,
      "Cst Cofins": "09",
      "Cofins": 1.87,
      "Cest": "4466586",
      "CTS": "bmKr",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 21.81,
      "Pr. Venda 1": 52.19,
      "Pr. Venda 2": 92.16
    },
    {
      "Código": "1048",
      "Descrição": "Voluptatem neque at ea fuga",
      "Emp": "2",
      "Descrição Reduzida": "Consequatur",
      "Comple": "Illum",
      "Cod. Categ.": "944",
      "Catego": "Blanditiis",
      "Cod. Marca": "777",
      "Marca": "Novaes",
      "Diretiva": "Tenetur",
      "Bal.": true,
      "Codigo Barras": "3859153589903",
      "Codigo NCM": "89118695",
      "Vasilh.": true,
      "CST": "54",
      "Cst Pis": "68",
      "Pis": 1.22,
      "Cst Cofins": "64",
      "Cofins": 2.68,
      "Cest": "7214631",
      "CTS": "rUov",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 70.5,
      "Pr. Venda 1": 13.43,
      "Pr. Venda 2": 41.16
    },
    {
      "Código": "1049",
      "Descrição": "Vel earum ipsam quod minus",
      "Emp": "3",
      "Descrição Reduzida": "Veritatis",
      "Comple": "Provident",
      "Cod. Categ.": "538",
      "Catego": "Quibusdam",
      "Cod. Marca": "877",
      "Marca": "da Conceição",
      "Diretiva": "Similique",
      "Bal.": true,
      "Codigo Barras": "0323274746932",
      "Codigo NCM": "98751744",
      "Vasilh.": false,
      "CST": "94",
      "Cst Pis": "64",
      "Pis": 1.06,
      "Cst Cofins": "29",
      "Cofins": 1.26,
      "Cest": "4959752",
      "CTS": "Valm",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 28.26,
      "Pr. Venda 1": 28.93,
      "Pr. Venda 2": 63.84
    },
    {
      "Código": "1050",
      "Descrição": "Nemo aut consequuntur",
      "Emp": "1",
      "Descrição Reduzida": "Nostrum",
      "Comple": "Aperiam",
      "Cod. Categ.": "734",
      "Catego": "Tempore",
      "Cod. Marca": "311",
      "Marca": "Aragão",
      "Diretiva": "Sapiente",
      "Bal.": false,
      "Codigo Barras": "2695042782465",
      "Codigo NCM": "32992238",
      "Vasilh.": true,
      "CST": "25",
      "Cst Pis": "13",
      "Pis": 1.73,
      "Cst Cofins": "70",
      "Cofins": 1.05,
      "Cest": "2698649",
      "CTS": "nTwR",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 79.99,
      "Pr. Venda 1": 97.66,
      "Pr. Venda 2": 35.31
    },
    {
      "Código": "1051",
      "Descrição": "Esse ex a in",
      "Emp": "2",
      "Descrição Reduzida": "Officiis",
      "Comple": "Placeat",
      "Cod. Categ.": "273",
      "Catego": "Sed",
      "Cod. Marca": "476",
      "Marca": "Freitas Dias - ME",
      "Diretiva": "Hic",
      "Bal.": true,
      "Codigo Barras": "3292698747146",
      "Codigo NCM": "97876593",
      "Vasilh.": true,
      "CST": "79",
      "Cst Pis": "82",
      "Pis": 1.17,
      "Cst Cofins": "65",
      "Cofins": 1.33,
      "Cest": "6504098",
      "CTS": "ymqg",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 51.84,
      "Pr. Venda 1": 56.48,
      "Pr. Venda 2": 78.0
    },
    {
      "Código": "1052",
      "Descrição": "Quisquam officia hic dolore",
      "Emp": "1",
      "Descrição Reduzida": "Commodi",
      "Comple": "Vel",
      "Cod. Categ.": "825",
      "Catego": "Laborum",
      "Cod. Marca": "557",
      "Marca": "Barbosa Azevedo e Filhos",
      "Diretiva": "Voluptatem",
      "Bal.": false,
      "Codigo Barras": "6530889703302",
      "Codigo NCM": "38374296",
      "Vasilh.": false,
      "CST": "98",
      "Cst Pis": "13",
      "Pis": 1.2,
      "Cst Cofins": "82",
      "Cofins": 1.37,
      "Cest": "8327861",
      "CTS": "dQbp",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 66.91,
      "Pr. Venda 1": 33.51,
      "Pr. Venda 2": 39.72
    },
    {
      "Código": "1053",
      "Descrição": "Expedita eos unde",
      "Emp": "3",
      "Descrição Reduzida": "Modi",
      "Comple": "Quisquam",
      "Cod. Categ.": "757",
      "Catego": "Eius",
      "Cod. Marca": "747",
      "Marca": "Barros",
      "Diretiva": "Itaque",
      "Bal.": false,
      "Codigo Barras": "1610239867405",
      "Codigo NCM": "31591711",
      "Vasilh.": true,
      "CST": "51",
      "Cst Pis": "81",
      "Pis": 1.7,
      "Cst Cofins": "12",
      "Cofins": 2.97,
      "Cest": "2002522",
      "CTS": "wgkJ",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 25.08,
      "Pr. Venda 1": 79.36,
      "Pr. Venda 2": 64.63
    },
    {
      "Código": "1054",
      "Descrição": "Ut hic illo dignissimos",
      "Emp": "5",
      "Descrição Reduzida": "Dolore",
      "Comple": "Repellat",
      "Cod. Categ.": "280",
      "Catego": "Saepe",
      "Cod. Marca": "985",
      "Marca": "Araújo",
      "Diretiva": "Dolorum",
      "Bal.": true,
      "Codigo Barras": "4852601968519",
      "Codigo NCM": "20502058",
      "Vasilh.": true,
      "CST": "11",
      "Cst Pis": "38",
      "Pis": 1.11,
      "Cst Cofins": "70",
      "Cofins": 2.76,
      "Cest": "9927671",
      "CTS": "kVHL",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 40.58,
      "Pr. Venda 1": 83.81,
      "Pr. Venda 2": 98.52
    },
    {
      "Código": "1055",
      "Descrição": "Voluptates unde at a",
      "Emp": "3",
      "Descrição Reduzida": "Autem",
      "Comple": "Aspernatur",
      "Cod. Categ.": "133",
      "Catego": "Laborum",
      "Cod. Marca": "995",
      "Marca": "Pereira",
      "Diretiva": "Amet",
      "Bal.": true,
      "Codigo Barras": "7758941753310",
      "Codigo NCM": "91827020",
      "Vasilh.": true,
      "CST": "48",
      "Cst Pis": "17",
      "Pis": 1.7,
      "Cst Cofins": "80",
      "Cofins": 2.57,
      "Cest": "2875275",
      "CTS": "WSUi",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 97.62,
      "Pr. Venda 1": 39.25,
      "Pr. Venda 2": 89.24
    },
    {
      "Código": "1056",
      "Descrição": "Aut occaecati officia omnis",
      "Emp": "1",
      "Descrição Reduzida": "Iste",
      "Comple": "Eos",
      "Cod. Categ.": "353",
      "Catego": "Voluptatum",
      "Cod. Marca": "390",
      "Marca": "Cunha",
      "Diretiva": "Voluptate",
      "Bal.": false,
      "Codigo Barras": "6657837364832",
      "Codigo NCM": "40420392",
      "Vasilh.": false,
      "CST": "49",
      "Cst Pis": "76",
      "Pis": 1.07,
      "Cst Cofins": "19",
      "Cofins": 1.33,
      "Cest": "1490525",
      "CTS": "BcAR",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 62.43,
      "Pr. Venda 1": 35.35,
      "Pr. Venda 2": 53.47
    },
    {
      "Código": "1057",
      "Descrição": "Ex tenetur corrupti",
      "Emp": "4",
      "Descrição Reduzida": "Quia",
      "Comple": "Voluptas",
      "Cod. Categ.": "852",
      "Catego": "Quo",
      "Cod. Marca": "243",
      "Marca": "Viana Pinto S.A.",
      "Diretiva": "Eius",
      "Bal.": true,
      "Codigo Barras": "2358906718085",
      "Codigo NCM": "21310539",
      "Vasilh.": true,
      "CST": "72",
      "Cst Pis": "10",
      "Pis": 1.91,
      "Cst Cofins": "06",
      "Cofins": 1.14,
      "Cest": "5290032",
      "CTS": "SAEz",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 31.47,
      "Pr. Venda 1": 14.04,
      "Pr. Venda 2": 80.02
    },
    {
      "Código": "1058",
      "Descrição": "Animi provident aut",
      "Emp": "4",
      "Descrição Reduzida": "Ratione",
      "Comple": "Autem",
      "Cod. Categ.": "610",
      "Catego": "In",
      "Cod. Marca": "596",
      "Marca": "Azevedo S/A",
      "Diretiva": "Cum",
      "Bal.": false,
      "Codigo Barras": "1157719506527",
      "Codigo NCM": "14926292",
      "Vasilh.": false,
      "CST": "72",
      "Cst Pis": "96",
      "Pis": 1.63,
      "Cst Cofins": "86",
      "Cofins": 1.18,
      "Cest": "4661359",
      "CTS": "spGN",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 33.2,
      "Pr. Venda 1": 44.05,
      "Pr. Venda 2": 22.09
    },
    {
      "Código": "1059",
      "Descrição": "Sunt at itaque fugiat a iure",
      "Emp": "1",
      "Descrição Reduzida": "Voluptate",
      "Comple": "Magni",
      "Cod. Categ.": "593",
      "Catego": "Voluptate",
      "Cod. Marca": "497",
      "Marca": "Mendes Teixeira S.A.",
      "Diretiva": "Porro",
      "Bal.": false,
      "Codigo Barras": "7033585076170",
      "Codigo NCM": "25926689",
      "Vasilh.": true,
      "CST": "93",
      "Cst Pis": "62",
      "Pis": 1.88,
      "Cst Cofins": "54",
      "Cofins": 2.45,
      "Cest": "6116925",
      "CTS": "lfha",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 48.0,
      "Pr. Venda 1": 68.31,
      "Pr. Venda 2": 15.88
    },
    {
      "Código": "1060",
      "Descrição": "Quidem numquam inventore",
      "Emp": "4",
      "Descrição Reduzida": "Tenetur",
      "Comple": "Labore",
      "Cod. Categ.": "928",
      "Catego": "Molestias",
      "Cod. Marca": "919",
      "Marca": "da Cruz",
      "Diretiva": "Quod",
      "Bal.": false,
      "Codigo Barras": "8700904621210",
      "Codigo NCM": "49610860",
      "Vasilh.": true,
      "CST": "84",
      "Cst Pis": "85",
      "Pis": 1.7,
      "Cst Cofins": "85",
      "Cofins": 1.42,
      "Cest": "4600705",
      "CTS": "xwFS",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 47.49,
      "Pr. Venda 1": 93.62,
      "Pr. Venda 2": 56.67
    },
    {
      "Código": "1061",
      "Descrição": "Fugiat beatae voluptatum",
      "Emp": "5",
      "Descrição Reduzida": "Nam",
      "Comple": "Nobis",
      "Cod. Categ.": "762",
      "Catego": "Sequi",
      "Cod. Marca": "755",
      "Marca": "Ferreira S/A",
      "Diretiva": "Atque",
      "Bal.": false,
      "Codigo Barras": "8823809354363",
      "Codigo NCM": "59284487",
      "Vasilh.": true,
      "CST": "91",
      "Cst Pis": "68",
      "Pis": 1.25,
      "Cst Cofins": "84",
      "Cofins": 2.53,
      "Cest": "8506641",
      "CTS": "NSjO",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 37.57,
      "Pr. Venda 1": 61.05,
      "Pr. Venda 2": 86.46
    },
    {
      "Código": "1062",
      "Descrição": "Numquam quam ex numquam",
      "Emp": "2",
      "Descrição Reduzida": "Necessitatibus",
      "Comple": "Occaecati",
      "Cod. Categ.": "479",
      "Catego": "Incidunt",
      "Cod. Marca": "406",
      "Marca": "Cardoso",
      "Diretiva": "Cupiditate",
      "Bal.": true,
      "Codigo Barras": "9435202484135",
      "Codigo NCM": "31780987",
      "Vasilh.": true,
      "CST": "13",
      "Cst Pis": "63",
      "Pis": 1.23,
      "Cst Cofins": "57",
      "Cofins": 2.27,
      "Cest": "9238783",
      "CTS": "ZMTS",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 46.64,
      "Pr. Venda 1": 83.66,
      "Pr. Venda 2": 91.68
    },
    {
      "Código": "1063",
      "Descrição": "Totam atque nihil odio",
      "Emp": "1",
      "Descrição Reduzida": "Labore",
      "Comple": "Quod",
      "Cod. Categ.": "517",
      "Catego": "Suscipit",
      "Cod. Marca": "936",
      "Marca": "Duarte",
      "Diretiva": "Minima",
      "Bal.": false,
      "Codigo Barras": "0834832927958",
      "Codigo NCM": "59581932",
      "Vasilh.": false,
      "CST": "74",
      "Cst Pis": "44",
      "Pis": 1.53,
      "Cst Cofins": "72",
      "Cofins": 1.91,
      "Cest": "4476199",
      "CTS": "FwEU",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 74.79,
      "Pr. Venda 1": 73.91,
      "Pr. Venda 2": 50.05
    },
    {
      "Código": "1064",
      "Descrição": "Eos ut assumenda",
      "Emp": "1",
      "Descrição Reduzida": "Ullam",
      "Comple": "Cumque",
      "Cod. Categ.": "559",
      "Catego": "Minus",
      "Cod. Marca": "632",
      "Marca": "da Costa",
      "Diretiva": "Ducimus",
      "Bal.": true,
      "Codigo Barras": "9316660740844",
      "Codigo NCM": "94274183",
      "Vasilh.": true,
      "CST": "22",
      "Cst Pis": "12",
      "Pis": 1.49,
      "Cst Cofins": "64",
      "Cofins": 1.99,
      "Cest": "6447910",
      "CTS": "sDsg",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 23.05,
      "Pr. Venda 1": 24.1,
      "Pr. Venda 2": 22.49
    },
    {
      "Código": "1065",
      "Descrição": "Vel quis temporibus odit aut",
      "Emp": "4",
      "Descrição Reduzida": "Reprehenderit",
      "Comple": "Delectus",
      "Cod. Categ.": "643",
      "Catego": "Labore",
      "Cod. Marca": "895",
      "Marca": "Freitas",
      "Diretiva": "Iste",
      "Bal.": true,
      "Codigo Barras": "9151142117536",
      "Codigo NCM": "17414365",
      "Vasilh.": false,
      "CST": "82",
      "Cst Pis": "93",
      "Pis": 1.26,
      "Cst Cofins": "32",
      "Cofins": 2.42,
      "Cest": "5149673",
      "CTS": "llQc",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 76.27,
      "Pr. Venda 1": 36.05,
      "Pr. Venda 2": 58.89
    },
    {
      "Código": "1066",
      "Descrição": "Vero sunt labore maiores",
      "Emp": "2",
      "Descrição Reduzida": "Dicta",
      "Comple": "Voluptates",
      "Cod. Categ.": "721",
      "Catego": "Modi",
      "Cod. Marca": "967",
      "Marca": "Monteiro",
      "Diretiva": "Commodi",
      "Bal.": false,
      "Codigo Barras": "0035094204379",
      "Codigo NCM": "95384074",
      "Vasilh.": true,
      "CST": "02",
      "Cst Pis": "35",
      "Pis": 1.45,
      "Cst Cofins": "51",
      "Cofins": 2.14,
      "Cest": "6218357",
      "CTS": "IDyY",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 72.32,
      "Pr. Venda 1": 14.65,
      "Pr. Venda 2": 62.52
    },
    {
      "Código": "1067",
      "Descrição": "Culpa sapiente quos officia",
      "Emp": "1",
      "Descrição Reduzida": "Quis",
      "Comple": "Voluptate",
      "Cod. Categ.": "217",
      "Catego": "Reprehenderit",
      "Cod. Marca": "845",
      "Marca": "Peixoto - ME",
      "Diretiva": "Voluptate",
      "Bal.": false,
      "Codigo Barras": "8809936060209",
      "Codigo NCM": "85128557",
      "Vasilh.": false,
      "CST": "48",
      "Cst Pis": "64",
      "Pis": 0.77,
      "Cst Cofins": "35",
      "Cofins": 2.76,
      "Cest": "9228536",
      "CTS": "VfSx",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 15.66,
      "Pr. Venda 1": 44.2,
      "Pr. Venda 2": 33.69
    },
    {
      "Código": "1068",
      "Descrição": "Dicta ratione minus ad",
      "Emp": "3",
      "Descrição Reduzida": "Sed",
      "Comple": "Impedit",
      "Cod. Categ.": "796",
      "Catego": "Eum",
      "Cod. Marca": "701",
      "Marca": "da Costa S/A",
      "Diretiva": "Delectus",
      "Bal.": true,
      "Codigo Barras": "6532784038244",
      "Codigo NCM": "51446625",
      "Vasilh.": false,
      "CST": "94",
      "Cst Pis": "30",
      "Pis": 1.53,
      "Cst Cofins": "11",
      "Cofins": 1.85,
      "Cest": "9448865",
      "CTS": "mSck",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 79.71,
      "Pr. Venda 1": 66.93,
      "Pr. Venda 2": 57.41
    },
    {
      "Código": "1069",
      "Descrição": "Soluta error quia nulla",
      "Emp": "1",
      "Descrição Reduzida": "Necessitatibus",
      "Comple": "Quam",
      "Cod. Categ.": "701",
      "Catego": "Saepe",
      "Cod. Marca": "996",
      "Marca": "Teixeira S/A",
      "Diretiva": "Ullam",
      "Bal.": true,
      "Codigo Barras": "0919648481419",
      "Codigo NCM": "70584347",
      "Vasilh.": true,
      "CST": "40",
      "Cst Pis": "74",
      "Pis": 1.58,
      "Cst Cofins": "00",
      "Cofins": 2.6,
      "Cest": "4979441",
      "CTS": "evpj",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 61.16,
      "Pr. Venda 1": 76.8,
      "Pr. Venda 2": 25.42
    },
    {
      "Código": "1070",
      "Descrição": "Sed sed occaecati aspernatur",
      "Emp": "4",
      "Descrição Reduzida": "Incidunt",
      "Comple": "Labore",
      "Cod. Categ.": "494",
      "Catego": "Eligendi",
      "Cod. Marca": "736",
      "Marca": "Freitas",
      "Diretiva": "Pariatur",
      "Bal.": true,
      "Codigo Barras": "8309905079558",
      "Codigo NCM": "40517014",
      "Vasilh.": true,
      "CST": "32",
      "Cst Pis": "85",
      "Pis": 1.77,
      "Cst Cofins": "09",
      "Cofins": 1.59,
      "Cest": "2305938",
      "CTS": "eQfI",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 54.92,
      "Pr. Venda 1": 96.11,
      "Pr. Venda 2": 71.98
    },
    {
      "Código": "1071",
      "Descrição": "Fugit odit dolorum odit",
      "Emp": "1",
      "Descrição Reduzida": "Ut",
      "Comple": "Harum",
      "Cod. Categ.": "280",
      "Catego": "Corporis",
      "Cod. Marca": "629",
      "Marca": "Fogaça",
      "Diretiva": "Voluptas",
      "Bal.": false,
      "Codigo Barras": "0905711254622",
      "Codigo NCM": "43198180",
      "Vasilh.": false,
      "CST": "09",
      "Cst Pis": "20",
      "Pis": 1.41,
      "Cst Cofins": "57",
      "Cofins": 2.98,
      "Cest": "2672938",
      "CTS": "ZPsi",
      "Ativo": true,
      "Bloq.": true,
      "Pr. Venda": 66.37,
      "Pr. Venda 1": 23.88,
      "Pr. Venda 2": 82.07
    },
    {
      "Código": "1072",
      "Descrição": "Voluptates earum sequi",
      "Emp": "4",
      "Descrição Reduzida": "Libero",
      "Comple": "Quae",
      "Cod. Categ.": "922",
      "Catego": "Accusamus",
      "Cod. Marca": "380",
      "Marca": "Pires S.A.",
      "Diretiva": "Voluptatem",
      "Bal.": true,
      "Codigo Barras": "5088207819873",
      "Codigo NCM": "15135684",
      "Vasilh.": false,
      "CST": "36",
      "Cst Pis": "38",
      "Pis": 0.88,
      "Cst Cofins": "91",
      "Cofins": 2.28,
      "Cest": "2882306",
      "CTS": "Osrp",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 40.11,
      "Pr. Venda 1": 93.09,
      "Pr. Venda 2": 89.02
    },
    {
      "Código": "1073",
      "Descrição": "Quibusdam velit delectus",
      "Emp": "5",
      "Descrição Reduzida": "Consectetur",
      "Comple": "Impedit",
      "Cod. Categ.": "579",
      "Catego": "Voluptas",
      "Cod. Marca": "355",
      "Marca": "Moraes",
      "Diretiva": "Tempore",
      "Bal.": true,
      "Codigo Barras": "9192933838674",
      "Codigo NCM": "13884090",
      "Vasilh.": false,
      "CST": "07",
      "Cst Pis": "69",
      "Pis": 1.29,
      "Cst Cofins": "42",
      "Cofins": 2.68,
      "Cest": "8276317",
      "CTS": "yGsh",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 55.62,
      "Pr. Venda 1": 75.64,
      "Pr. Venda 2": 29.4
    },
    {
      "Código": "1074",
      "Descrição": "Iusto ex accusantium quia",
      "Emp": "3",
      "Descrição Reduzida": "Dolore",
      "Comple": "Sequi",
      "Cod. Categ.": "467",
      "Catego": "Doloribus",
      "Cod. Marca": "433",
      "Marca": "da Luz Nogueira - EI",
      "Diretiva": "Iusto",
      "Bal.": false,
      "Codigo Barras": "1381569337165",
      "Codigo NCM": "18017856",
      "Vasilh.": false,
      "CST": "56",
      "Cst Pis": "08",
      "Pis": 1.55,
      "Cst Cofins": "30",
      "Cofins": 2.46,
      "Cest": "6224585",
      "CTS": "Ixfj",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 89.08,
      "Pr. Venda 1": 90.21,
      "Pr. Venda 2": 81.69
    },
    {
      "Código": "1075",
      "Descrição": "Dolores quod velit",
      "Emp": "5",
      "Descrição Reduzida": "Illo",
      "Comple": "Amet",
      "Cod. Categ.": "295",
      "Catego": "Optio",
      "Cod. Marca": "337",
      "Marca": "Duarte",
      "Diretiva": "Quos",
      "Bal.": true,
      "Codigo Barras": "2890965030833",
      "Codigo NCM": "54878896",
      "Vasilh.": false,
      "CST": "10",
      "Cst Pis": "32",
      "Pis": 1.88,
      "Cst Cofins": "26",
      "Cofins": 2.92,
      "Cest": "4474512",
      "CTS": "TSRu",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 15.66,
      "Pr. Venda 1": 53.72,
      "Pr. Venda 2": 60.19
    },
    {
      "Código": "1076",
      "Descrição": "Iure enim ullam",
      "Emp": "3",
      "Descrição Reduzida": "Rem",
      "Comple": "Optio",
      "Cod. Categ.": "492",
      "Catego": "Voluptate",
      "Cod. Marca": "861",
      "Marca": "Jesus",
      "Diretiva": "Porro",
      "Bal.": true,
      "Codigo Barras": "8334700709041",
      "Codigo NCM": "47137151",
      "Vasilh.": true,
      "CST": "19",
      "Cst Pis": "38",
      "Pis": 1.42,
      "Cst Cofins": "97",
      "Cofins": 2.85,
      "Cest": "6051360",
      "CTS": "tkBr",
      "Ativo": false,
      "Bloq.": true,
      "Pr. Venda": 85.99,
      "Pr. Venda 1": 55.51,
      "Pr. Venda 2": 51.31
    },
    {
      "Código": "1077",
      "Descrição": "Quibusdam iure velit quis",
      "Emp": "2",
      "Descrição Reduzida": "Quae",
      "Comple": "Recusandae",
      "Cod. Categ.": "789",
      "Catego": "Eius",
      "Cod. Marca": "676",
      "Marca": "da Conceição",
      "Diretiva": "Accusantium",
      "Bal.": false,
      "Codigo Barras": "9660044135833",
      "Codigo NCM": "90299510",
      "Vasilh.": true,
      "CST": "39",
      "Cst Pis": "90",
      "Pis": 1.54,
      "Cst Cofins": "96",
      "Cofins": 2.77,
      "Cest": "5327926",
      "CTS": "tQkq",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 43.9,
      "Pr. Venda 1": 26.22,
      "Pr. Venda 2": 40.48
    },
    {
      "Código": "1078",
      "Descrição": "Libero harum nihil quam ea",
      "Emp": "5",
      "Descrição Reduzida": "Voluptatibus",
      "Comple": "Veniam",
      "Cod. Categ.": "205",
      "Catego": "Et",
      "Cod. Marca": "616",
      "Marca": "Carvalho e Filhos",
      "Diretiva": "Ex",
      "Bal.": false,
      "Codigo Barras": "2225538127076",
      "Codigo NCM": "26673754",
      "Vasilh.": false,
      "CST": "57",
      "Cst Pis": "61",
      "Pis": 1.76,
      "Cst Cofins": "27",
      "Cofins": 1.53,
      "Cest": "8989042",
      "CTS": "Quts",
      "Ativo": true,
      "Bloq.": false,
      "Pr. Venda": 21.95,
      "Pr. Venda 1": 43.3,
      "Pr. Venda 2": 20.35
    },
    {
      "Código": "1079",
      "Descrição": "Eum laudantium corporis modi",
      "Emp": "3",
      "Descrição Reduzida": "Doloremque",
      "Comple": "Impedit",
      "Cod. Categ.": "724",
      "Catego": "Rerum",
      "Cod. Marca": "329",
      "Marca": "Moraes",
      "Diretiva": "Voluptatum",
      "Bal.": true,
      "Codigo Barras": "3534396134546",
      "Codigo NCM": "75594043",
      "Vasilh.": false,
      "CST": "51",
      "Cst Pis": "88",
      "Pis": 1.12,
      "Cst Cofins": "19",
      "Cofins": 1.35,
      "Cest": "3399292",
      "CTS": "AFmI",
      "Ativo": false,
      "Bloq.": false,
      "Pr. Venda": 57.32,
      "Pr. Venda 1": 22.37,
      "Pr. Venda 2": 92.81
    }
  ]
}