// app/layout.tsx (ou pages/_app.tsx)
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterComponent from "../components/Shared/Footer";
import HeaderComponent from "../components/Shared/Header";
import { ReactQueryProvider } from "../providers/ReactQueryClientProvider";
import { Suspense } from "react";
import { UserProvider } from "@cardapio/hooks/auth/userContext";
import { Toaster } from "@cardapio/components/Shared/ui/sonner";
import { CartGlobalClient } from "@cardapio/components/Shared/cart/CartGlobalClient";
import { ThemeProvider } from "@cardapio/components/Shared/theme/ThemeProvider";
import { LojaFechadaBannerGlobal } from "@cardapio/components/Shared/LojaFechadaBannerGlobal";
import { LojaStatusHeaderGlobal } from "@cardapio/components/Shared/LojaStatusHeaderGlobal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cardápio Online",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={null}>
          <ReactQueryProvider>
            <ThemeProvider />
            <UserProvider>
              <div className="min-h-screen bg-gray-50 flex justify-center">
                <div className="w-full max-w-md bg-white min-h-screen shadow-xl relative flex flex-col">
                  <Toaster
                    position="top-right"
                    richColors
                    style={{
                      /* sucesso (toast.success) */
                      "--success-bg": "#22c55e",
                      "--success-text": "#ffffff",
                      "--success-border": "#16a34a",

                      /* erro (toast.error → variante 'destructive') */
                      "--destructive-bg": "#ffffff",
                      "--destructive-text": "#ef4444",
                      "--destructive-border": "#ef4444",
                    } as React.CSSProperties}
                  />
                  <Suspense fallback={null}>
                    <LojaStatusHeaderGlobal />
                  </Suspense>
                  <Suspense fallback={null}>
                    <HeaderComponent />
                  </Suspense>
                  <div className="flex-1">
                    <Suspense fallback={null}>
                      <LojaFechadaBannerGlobal />
                    </Suspense>
                    {children}
                  </div>
                  <FooterComponent />
                </div>
              </div>
              <CartGlobalClient />
            </UserProvider>
          </ReactQueryProvider>
        </Suspense>
      </body>
    </html>
  );
}
