// app/layout.tsx (ou pages/_app.tsx)
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterComponent from "../components/Shared/Footer";
import { ReactQueryProvider } from "../providers/ReactQueryClientProvider";
import { Suspense } from "react";
import { UserProvider } from "@cardapio/hooks/auth/userContext";
import { Toaster } from "@cardapio/components/Shared/ui/sonner";
import { CartGlobalClient } from "@cardapio/components/Shared/cart/CartGlobalClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cardápio Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense />
        <ReactQueryProvider>
          <UserProvider>
            <Toaster
              position="top-right"
              richColors
              style={{
                /* sucesso (toast.success) */
                "--success-bg": "#22c55e",
                "--success-text": "#ffffff",
                "--success-border": "#16a34a",

                /* erro (toast.error → variante 'destructive') */
                "--destructive-bg": "#ef4444",
                "--destructive-text": "#ffffff",
                "--destructive-border": "#dc2626",
              } as React.CSSProperties}
            />
            <div className="min-h-screen">
              {children}
            </div>
            <CartGlobalClient />
          </UserProvider>
        </ReactQueryProvider>
        <FooterComponent />
      </body>
    </html>
  );
}
