/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { BaseHttpRequest } from './core/BaseHttpRequest';
import type { OpenAPIConfig } from './core/OpenAPI';
import { FetchHttpRequest } from './core/FetchHttpRequest';
import { AdminBalcOPedidosService } from './services/AdminBalcOPedidosService';
import { AdminCadastrosAdicionaisService } from './services/AdminCadastrosAdicionaisService';
import { AdminCadastrosCategoriasService } from './services/AdminCadastrosCategoriasService';
import { AdminCadastrosClientesService } from './services/AdminCadastrosClientesService';
import { AdminCadastrosCombosService } from './services/AdminCadastrosCombosService';
import { AdminCadastrosEndereOsService } from './services/AdminCadastrosEndereOsService';
import { AdminCadastrosEntregadoresService } from './services/AdminCadastrosEntregadoresService';
import { AdminCadastrosMeiosDePagamentoService } from './services/AdminCadastrosMeiosDePagamentoService';
import { AdminCadastrosParceirosService } from './services/AdminCadastrosParceirosService';
import { AdminCadastrosProdutosService } from './services/AdminCadastrosProdutosService';
import { AdminCadastrosRegiEsDeEntregaService } from './services/AdminCadastrosRegiEsDeEntregaService';
import { AdminCadastrosVitrinesService } from './services/AdminCadastrosVitrinesService';
import { AdminCaixasService } from './services/AdminCaixasService';
import { AdminDeliveryAcertosDeEntregadoresService } from './services/AdminDeliveryAcertosDeEntregadoresService';
import { AdminDeliveryCuponsService } from './services/AdminDeliveryCuponsService';
import { AdminDeliveryPagamentosService } from './services/AdminDeliveryPagamentosService';
import { AdminDeliveryPedidosService } from './services/AdminDeliveryPedidosService';
import { AdminMensuraCategoriasService } from './services/AdminMensuraCategoriasService';
import { AdminMensuraEmpresasService } from './services/AdminMensuraEmpresasService';
import { AdminMensuraEnderecosService } from './services/AdminMensuraEnderecosService';
import { AdminMensuraGeoapifyService } from './services/AdminMensuraGeoapifyService';
import { AdminMensuraReceitasService } from './services/AdminMensuraReceitasService';
import { AdminMensuraUsuariosService } from './services/AdminMensuraUsuariosService';
import { AdminMesasService } from './services/AdminMesasService';
import { AdminMesasPedidosService } from './services/AdminMesasPedidosService';
import { AdminMinIoService } from './services/AdminMinIoService';
import { AdminRelatRiosPanorMicoDiRioService } from './services/AdminRelatRiosPanorMicoDiRioService';
import { AdminRotasDeAdministraOService } from './services/AdminRotasDeAdministraOService';
import { ApiBalcOService } from './services/ApiBalcOService';
import { ApiCadastrosService } from './services/ApiCadastrosService';
import { ApiCaixaService } from './services/ApiCaixaService';
import { ApiMesasService } from './services/ApiMesasService';
import { ApiNotificationsService } from './services/ApiNotificationsService';
import { ApiRelatRiosService } from './services/ApiRelatRiosService';
import { AuthService } from './services/AuthService';
import { ClientBalcOPedidosService } from './services/ClientBalcOPedidosService';
import { ClientCadastrosAdicionaisService } from './services/ClientCadastrosAdicionaisService';
import { ClientCadastrosCategoriasService } from './services/ClientCadastrosCategoriasService';
import { ClientCadastrosClientesService } from './services/ClientCadastrosClientesService';
import { ClientCadastrosEndereOsService } from './services/ClientCadastrosEndereOsService';
import { ClientCadastrosMeiosDePagamentoService } from './services/ClientCadastrosMeiosDePagamentoService';
import { ClientDeliveryPagamentosService } from './services/ClientDeliveryPagamentosService';
import { ClientDeliveryPedidosService } from './services/ClientDeliveryPedidosService';
import { ClientMensuraGeoapifyService } from './services/ClientMensuraGeoapifyService';
import { ClientRotasDeClienteService } from './services/ClientRotasDeClienteService';
import { DefaultService } from './services/DefaultService';
import { EventsService } from './services/EventsService';
import { GatewayOrquestradorService } from './services/GatewayOrquestradorService';
import { HistoricoService } from './services/HistoricoService';
import { NotificationsService } from './services/NotificationsService';
import { PedidoNotificationsService } from './services/PedidoNotificationsService';
import { PublicCadastrosParceirosService } from './services/PublicCadastrosParceirosService';
import { PublicDeliveryHomeService } from './services/PublicDeliveryHomeService';
import { PublicDeliveryMercadoPagoWebhooksService } from './services/PublicDeliveryMercadoPagoWebhooksService';
import { PublicDeliveryPrinterService } from './services/PublicDeliveryPrinterService';
import { PublicMensuraEmpresasService } from './services/PublicMensuraEmpresasService';
import { PublicRotasPBlicasService } from './services/PublicRotasPBlicasService';
import { RabbitmqService } from './services/RabbitmqService';
import { SubscriptionsService } from './services/SubscriptionsService';
import { WebsocketService } from './services/WebsocketService';
type HttpRequestConstructor = new (config: OpenAPIConfig) => BaseHttpRequest;
export class MensuraApiClient {
    public readonly adminBalcOPedidos: AdminBalcOPedidosService;
    public readonly adminCadastrosAdicionais: AdminCadastrosAdicionaisService;
    public readonly adminCadastrosCategorias: AdminCadastrosCategoriasService;
    public readonly adminCadastrosClientes: AdminCadastrosClientesService;
    public readonly adminCadastrosCombos: AdminCadastrosCombosService;
    public readonly adminCadastrosEndereOs: AdminCadastrosEndereOsService;
    public readonly adminCadastrosEntregadores: AdminCadastrosEntregadoresService;
    public readonly adminCadastrosMeiosDePagamento: AdminCadastrosMeiosDePagamentoService;
    public readonly adminCadastrosParceiros: AdminCadastrosParceirosService;
    public readonly adminCadastrosProdutos: AdminCadastrosProdutosService;
    public readonly adminCadastrosRegiEsDeEntrega: AdminCadastrosRegiEsDeEntregaService;
    public readonly adminCadastrosVitrines: AdminCadastrosVitrinesService;
    public readonly adminCaixas: AdminCaixasService;
    public readonly adminDeliveryAcertosDeEntregadores: AdminDeliveryAcertosDeEntregadoresService;
    public readonly adminDeliveryCupons: AdminDeliveryCuponsService;
    public readonly adminDeliveryPagamentos: AdminDeliveryPagamentosService;
    public readonly adminDeliveryPedidos: AdminDeliveryPedidosService;
    public readonly adminMensuraCategorias: AdminMensuraCategoriasService;
    public readonly adminMensuraEmpresas: AdminMensuraEmpresasService;
    public readonly adminMensuraEnderecos: AdminMensuraEnderecosService;
    public readonly adminMensuraGeoapify: AdminMensuraGeoapifyService;
    public readonly adminMensuraReceitas: AdminMensuraReceitasService;
    public readonly adminMensuraUsuarios: AdminMensuraUsuariosService;
    public readonly adminMesas: AdminMesasService;
    public readonly adminMesasPedidos: AdminMesasPedidosService;
    public readonly adminMinIo: AdminMinIoService;
    public readonly adminRelatRiosPanorMicoDiRio: AdminRelatRiosPanorMicoDiRioService;
    public readonly adminRotasDeAdministraO: AdminRotasDeAdministraOService;
    public readonly apiBalcO: ApiBalcOService;
    public readonly apiCadastros: ApiCadastrosService;
    public readonly apiCaixa: ApiCaixaService;
    public readonly apiMesas: ApiMesasService;
    public readonly apiNotifications: ApiNotificationsService;
    public readonly apiRelatRios: ApiRelatRiosService;
    public readonly auth: AuthService;
    public readonly clientBalcOPedidos: ClientBalcOPedidosService;
    public readonly clientCadastrosAdicionais: ClientCadastrosAdicionaisService;
    public readonly clientCadastrosCategorias: ClientCadastrosCategoriasService;
    public readonly clientCadastrosClientes: ClientCadastrosClientesService;
    public readonly clientCadastrosEndereOs: ClientCadastrosEndereOsService;
    public readonly clientCadastrosMeiosDePagamento: ClientCadastrosMeiosDePagamentoService;
    public readonly clientDeliveryPagamentos: ClientDeliveryPagamentosService;
    public readonly clientDeliveryPedidos: ClientDeliveryPedidosService;
    public readonly clientMensuraGeoapify: ClientMensuraGeoapifyService;
    public readonly clientRotasDeCliente: ClientRotasDeClienteService;
    public readonly default: DefaultService;
    public readonly events: EventsService;
    public readonly gatewayOrquestrador: GatewayOrquestradorService;
    public readonly historico: HistoricoService;
    public readonly notifications: NotificationsService;
    public readonly pedidoNotifications: PedidoNotificationsService;
    public readonly publicCadastrosParceiros: PublicCadastrosParceirosService;
    public readonly publicDeliveryHome: PublicDeliveryHomeService;
    public readonly publicDeliveryMercadoPagoWebhooks: PublicDeliveryMercadoPagoWebhooksService;
    public readonly publicDeliveryPrinter: PublicDeliveryPrinterService;
    public readonly publicMensuraEmpresas: PublicMensuraEmpresasService;
    public readonly publicRotasPBlicas: PublicRotasPBlicasService;
    public readonly rabbitmq: RabbitmqService;
    public readonly subscriptions: SubscriptionsService;
    public readonly websocket: WebsocketService;
    public readonly request: BaseHttpRequest;
    constructor(config?: Partial<OpenAPIConfig>, HttpRequest: HttpRequestConstructor = FetchHttpRequest) {
        this.request = new HttpRequest({
            BASE: config?.BASE ?? 'https://teste2.mensuraapi.com.br',
            VERSION: config?.VERSION ?? '1.0.0',
            WITH_CREDENTIALS: config?.WITH_CREDENTIALS ?? false,
            CREDENTIALS: config?.CREDENTIALS ?? 'include',
            TOKEN: config?.TOKEN,
            USERNAME: config?.USERNAME,
            PASSWORD: config?.PASSWORD,
            HEADERS: config?.HEADERS,
            ENCODE_PATH: config?.ENCODE_PATH,
        });
        this.adminBalcOPedidos = new AdminBalcOPedidosService(this.request);
        this.adminCadastrosAdicionais = new AdminCadastrosAdicionaisService(this.request);
        this.adminCadastrosCategorias = new AdminCadastrosCategoriasService(this.request);
        this.adminCadastrosClientes = new AdminCadastrosClientesService(this.request);
        this.adminCadastrosCombos = new AdminCadastrosCombosService(this.request);
        this.adminCadastrosEndereOs = new AdminCadastrosEndereOsService(this.request);
        this.adminCadastrosEntregadores = new AdminCadastrosEntregadoresService(this.request);
        this.adminCadastrosMeiosDePagamento = new AdminCadastrosMeiosDePagamentoService(this.request);
        this.adminCadastrosParceiros = new AdminCadastrosParceirosService(this.request);
        this.adminCadastrosProdutos = new AdminCadastrosProdutosService(this.request);
        this.adminCadastrosRegiEsDeEntrega = new AdminCadastrosRegiEsDeEntregaService(this.request);
        this.adminCadastrosVitrines = new AdminCadastrosVitrinesService(this.request);
        this.adminCaixas = new AdminCaixasService(this.request);
        this.adminDeliveryAcertosDeEntregadores = new AdminDeliveryAcertosDeEntregadoresService(this.request);
        this.adminDeliveryCupons = new AdminDeliveryCuponsService(this.request);
        this.adminDeliveryPagamentos = new AdminDeliveryPagamentosService(this.request);
        this.adminDeliveryPedidos = new AdminDeliveryPedidosService(this.request);
        this.adminMensuraCategorias = new AdminMensuraCategoriasService(this.request);
        this.adminMensuraEmpresas = new AdminMensuraEmpresasService(this.request);
        this.adminMensuraEnderecos = new AdminMensuraEnderecosService(this.request);
        this.adminMensuraGeoapify = new AdminMensuraGeoapifyService(this.request);
        this.adminMensuraReceitas = new AdminMensuraReceitasService(this.request);
        this.adminMensuraUsuarios = new AdminMensuraUsuariosService(this.request);
        this.adminMesas = new AdminMesasService(this.request);
        this.adminMesasPedidos = new AdminMesasPedidosService(this.request);
        this.adminMinIo = new AdminMinIoService(this.request);
        this.adminRelatRiosPanorMicoDiRio = new AdminRelatRiosPanorMicoDiRioService(this.request);
        this.adminRotasDeAdministraO = new AdminRotasDeAdministraOService(this.request);
        this.apiBalcO = new ApiBalcOService(this.request);
        this.apiCadastros = new ApiCadastrosService(this.request);
        this.apiCaixa = new ApiCaixaService(this.request);
        this.apiMesas = new ApiMesasService(this.request);
        this.apiNotifications = new ApiNotificationsService(this.request);
        this.apiRelatRios = new ApiRelatRiosService(this.request);
        this.auth = new AuthService(this.request);
        this.clientBalcOPedidos = new ClientBalcOPedidosService(this.request);
        this.clientCadastrosAdicionais = new ClientCadastrosAdicionaisService(this.request);
        this.clientCadastrosCategorias = new ClientCadastrosCategoriasService(this.request);
        this.clientCadastrosClientes = new ClientCadastrosClientesService(this.request);
        this.clientCadastrosEndereOs = new ClientCadastrosEndereOsService(this.request);
        this.clientCadastrosMeiosDePagamento = new ClientCadastrosMeiosDePagamentoService(this.request);
        this.clientDeliveryPagamentos = new ClientDeliveryPagamentosService(this.request);
        this.clientDeliveryPedidos = new ClientDeliveryPedidosService(this.request);
        this.clientMensuraGeoapify = new ClientMensuraGeoapifyService(this.request);
        this.clientRotasDeCliente = new ClientRotasDeClienteService(this.request);
        this.default = new DefaultService(this.request);
        this.events = new EventsService(this.request);
        this.gatewayOrquestrador = new GatewayOrquestradorService(this.request);
        this.historico = new HistoricoService(this.request);
        this.notifications = new NotificationsService(this.request);
        this.pedidoNotifications = new PedidoNotificationsService(this.request);
        this.publicCadastrosParceiros = new PublicCadastrosParceirosService(this.request);
        this.publicDeliveryHome = new PublicDeliveryHomeService(this.request);
        this.publicDeliveryMercadoPagoWebhooks = new PublicDeliveryMercadoPagoWebhooksService(this.request);
        this.publicDeliveryPrinter = new PublicDeliveryPrinterService(this.request);
        this.publicMensuraEmpresas = new PublicMensuraEmpresasService(this.request);
        this.publicRotasPBlicas = new PublicRotasPBlicasService(this.request);
        this.rabbitmq = new RabbitmqService(this.request);
        this.subscriptions = new SubscriptionsService(this.request);
        this.websocket = new WebsocketService(this.request);
    }
}

